spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none # none:关闭spring session

# 在springboot的1.5版本可以这么写，2.0+版本就必须在代码中控制了，配置无效
#security:
#  basic:
#    enabled: false #关闭spring security

#关闭redis的健康检查，生产环境需要注释掉这个
management:
  health:
    redis:
      enabled: false

#配置安全相关
monkey:
  security:
    browser:
#      loginPage: /demo-signIn.html #自定义登录页面，如果不配置就用默认的标准登录页
#      loginType: REDIRECT #登录方式页面跳转，默认json
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/* #配置哪些接口需要被验证码拦截
      session:
        sessionInvalidUrl: /demo-session-invalid.html #session失效的跳转页面
#      signOutUrl: /demo-signOut.html #退出成功后的跳转页面
    oauth2:
      clients[0]: #多个应用的配置方式
        clientId: mkapp
        clientSecret: mkappSecret
        accessTokenValiditySeconds: 7200
      clients[1]:
        clientId: test
        clientSecret: test
  #微信配置
  wx:
    #微信的appid
    appid: wx6b7ceaa8d9a87338
    appsecret: 161272424db506f2694fca16d53bc170
    #获取code的scope
    scope: snsapi_userinfo
    #本网站api接口地址
    web-api-domain: http://pdyfii.natappfree.cc/api

server:
  session:
    timeout: 600 #单位是秒，session超时时间，在spring boot中session超时时间最少是1分钟，看源码可知道
#  port: 8088

#这里是给应用配置client-id和client-secret的地方（这里是单个配置方法，但是使用配置类以后就不用在这里写了）
#security:
#  oauth2:
#    client:
#      client-id: mkapp
#      client-secret: mkappSecret
