spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none #关闭spring session

#security:
#  basic:
#    enabled: false #关闭spring security

#关闭redis的健康检查，生产环境需要注释掉这个
management:
  health:
    redis:
      enabled: false

#配置安全相关
monkey:
  security:
#    browser:
#      loginPage: /demo-signIn.html #自定义登录页面，如果不配置就用默认的标准登录页
#      loginType: REDIRECT #登录方式页面跳转，默认json
    code:
      image:
        length: 6
        width: 100